# Armor seed rows with armour_category included
ARMOR_ROWS: list[tuple[str, str, int, str, int, bool, int, int, bool, int, str, int, bool, str, str]] = [
    ('leather-armor-plus-one', 'Leather Armor +1', 4000, 'gp', 11, True, 0, 0, False, 10, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Light'),
    ('padded-armor-plus-one', 'Padded Armor +1', 4000, 'gp', 11, True, 0, 0, True, 8, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Light'),
    ('shield-plus-one', 'Shield +1', 4000, 'gp', 2, False, 0, 0, False, 6, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Shield'),
    ('studded-leather-armor-plus-one', 'Studded Leather Armor +1', 4000, 'gp', 12, True, 0, 0, True, 13, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('leather-armor-plus-two', 'Leather Armor +2', 40000, 'gp', 11, True, 0, 0, False, 10, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Light'),
    ('padded-armor-plus-two', 'Padded Armor +2', 40000, 'gp', 11, True, 0, 0, True, 8, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Light'),
    ('shield-plus-two', 'Shield +2', 40000, 'gp', 2, False, 0, 0, False, 6, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Shield'),
    ('studded-leather-armor-plus-two', 'Studded Leather Armor +2', 40000, 'gp', 12, True, 0, 0, False, 13, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('leather-armor-plus-three', 'Leather Armor +3', 200000, 'gp', 11, True, 0, 0, False, 10, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Light'),
    ('padded-armor-plus-three', 'Padded Armor +3', 200000, 'gp', 11, True, 0, 0, True, 8, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Light'),
    ('shield-plus-three', 'Shield +3', 200000, 'gp', 2, False, 0, 0, False, 6, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Shield'),
    ('studded-leather-armor-plus-three', 'Studded Leather Armor +3', 200000, 'gp', 12, True, 0, 0, False, 13, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('breastplate-plus-one', 'Breastplate +1', 4000, 'gp', 14, True, 2, 0, False, 20, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('chain-mail-plus-one', 'Chain Mail +1', 4000, 'gp', 16, False, 0, 13, True, 55, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Heavy'),
    ('chain-shirt-plus-one', 'Chain Shirt +1', 4000, 'gp', 13, True, 2, 0, False, 20, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('half-plate-armor-plus-one', 'Half Plate Armor +1', 4000, 'gp', 15, True, 2, 0, True, 40, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('hide-armor-plus-one', 'Hide Armor +1', 4000, 'gp', 12, True, 2, 0, False, 12, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('plate-armor-plus-one', 'Plate Armor +1', 4000, 'gp', 18, False, 0, 15, True, 65, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Heavy'),
    ('ring-mail-plus-one', 'Ring Mail +1', 4000, 'gp', 14, False, 0, 0, True, 40, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Heavy'),
    ('scale-mail-plus-one', 'Scale Mail +1', 4000, 'gp', 14, True, 2, 0, True, 45, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('splint-armor-plus-one', 'Splint Armor +1', 4000, 'gp', 17, False, 0, 15, True, 60, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Heavy'),
    ('breastplate-plus-two', 'Breastplate +2', 40000, 'gp', 14, True, 2, 0, False, 20, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('chain-mail-plus-two', 'Chain Mail +2', 40000, 'gp', 16, False, 0, 13, True, 55, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Heavy'),
    ('chain-shirt-plus-two', 'Chain Shirt +2', 40000, 'gp', 13, True, 2, 0, False, 20, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('half-plate-armor-plus-two', 'Half Plate Armor +2', 40000, 'gp', 15, True, 2, 0, True, 40, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('hide-armor-plus-two', 'Hide Armor +2', 40000, 'gp', 12, True, 2, 0, False, 12, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('plate-armor-plus-two', 'Plate Armor +2', 40000, 'gp', 18, False, 0, 15, True, 65, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Heavy'),
    ('ring-mail-plus-two', 'Ring Mail +2', 40000, 'gp', 14, False, 0, 0, True, 40, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Heavy'),
    ('scale-mail-plus-two', 'Scale Mail +2', 40000, 'gp', 14, True, 2, 0, True, 45, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('splint-armor-plus-two', 'Splint Armor +2', 40000, 'gp', 17, False, 0, 15, True, 60, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Heavy'),
    ('breastplate-plus-three', 'Breastplate +3', 200000, 'gp', 14, True, 2, 0, False, 20, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('chain-mail-plus-three', 'Chain Mail +3', 200000, 'gp', 16, False, 0, 13, True, 55, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Heavy'),
    ('chain-shirt-plus-three', 'Chain Shirt +3', 200000, 'gp', 13, True, 2, 0, False, 20, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('half-plate-armor-plus-three', 'Half Plate Armor +3', 200000, 'gp', 15, True, 2, 0, True, 40, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('hide-armor-plus-three', 'Hide Armor +3', 200000, 'gp', 12, True, 2, 0, False, 12, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('plate-armor-plus-three', 'Plate Armor +3', 200000, 'gp', 18, False, 0, 15, True, 65, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Heavy'),
    ('ring-mail-plus-three', 'Ring Mail +3', 200000, 'gp', 14, False, 0, 0, True, 40, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Heavy'),
    ('scale-mail-plus-three', 'Scale Mail +3', 200000, 'gp', 14, True, 2, 0, True, 45, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('splint-armor-plus-three', 'Splint Armor +3', 200000, 'gp', 17, False, 0, 15, True, 60, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Heavy'),
    ('adamantine-breastplate', 'Adamantine Breastplate', 400, 'gp', 14, True, 2, 0, False, 20, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Medium'),
    ('adamantine-chain-mail', 'Adamantine Chain Mail', 400, 'gp', 16, False, 0, 13, True, 55, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Heavy'),
    ('adamantine-chain-shirt', 'Adamantine Chain Shirt', 400, 'gp', 13, True, 2, 0, False, 20, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Medium'),
    ('adamantine-half-plate-armor', 'Adamantine Half Plate Armor', 400, 'gp', 15, True, 2, 0, True, 40, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Medium'),
    ('adamantine-plate-armor', 'Adamantine Plate Armor', 400, 'gp', 18, False, 0, 15, True, 65, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Heavy'),
    ('adamantine-ring-mail', 'Adamantine Ring Mail', 400, 'gp', 14, False, 0, 0, True, 40, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Heavy'),
    ('adamantine-scale-mail', 'Adamantine Scale Mail', 400, 'gp', 14, True, 2, 0, True, 45, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Medium'),
    ('adamantine-splint-armor', 'Adamantine Splint Armor', 400, 'gp', 17, False, 0, 15, True, 60, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Heavy'),
]

WEAPON_ROWS: list[tuple[str, str, int, str, str, str, str, str, int, int, float, str, int, bool, str, str]] = [

    ('battleaxe-plus-one', 'Battleaxe +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 4,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Axe'),
    ('battleaxe-plus-two', 'Battleaxe +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 4,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Axe'),
    ('battleaxe-plus-three', 'Battleaxe +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 4,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Axe'),
    ('blowgun-plus-one', 'Blowgun +1', 4000, 'gp', 'Ranged', 'Martial Ranged', '1', 'piercing', 25, 100, 1,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Blowgun'),
    ('blowgun-plus-two', 'Blowgun +2', 40000, 'gp', 'Ranged', 'Martial Ranged', '1', 'piercing', 25, 100, 1,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Blowgun'),
    ('blowgun-plus-three', 'Blowgun +3', 200000, 'gp', 'Ranged', 'Martial Ranged', '1', 'piercing', 25, 100, 1,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Blowgun'),
    ('club-plus-one', 'Club +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d4', 'bludgeoning', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bludgeon'),
    ('club-plus-two', 'Club +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d4', 'bludgeoning', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bludgeon'),
    ('club-plus-three', 'Club +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d4', 'bludgeoning', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bludgeon'),

    ('crossbow-hand-plus-one', 'Crossbow, hand +1', 4000, 'gp', 'Ranged', 'Martial Ranged', '1d6', 'piercing', 30, 120,
     3, 'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bow'),
    ('crossbow-hand-plus-two', 'Crossbow, hand +2', 40000, 'gp', 'Ranged', 'Martial Ranged', '1d6', 'piercing', 30, 120,
     3, 'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bow'),
    ('crossbow-hand-plus-three', 'Crossbow, hand +3', 200000, 'gp', 'Ranged', 'Martial Ranged', '1d6', 'piercing', 30,
     120, 3, 'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary',
     'Bow'),
    ('crossbow-heavy-plus-one', 'Crossbow, heavy +1', 4000, 'gp', 'Ranged', 'Martial Ranged', '1d10', 'piercing', 100,
     400, 18, 'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bow'),
    ('crossbow-heavy-plus-two', 'Crossbow, heavy +2', 40000, 'gp', 'Ranged', 'Martial Ranged', '1d10', 'piercing', 100,
     400, 18, 'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare',
     'Bow'),
    ('crossbow-heavy-plus-three', 'Crossbow, heavy +3', 200000, 'gp', 'Ranged', 'Martial Ranged', '1d10', 'piercing',
     100, 400, 18, 'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary',
     'Bow'),
    ('crossbow-light-plus-one', 'Crossbow, light +1', 4000, 'gp', 'Ranged', 'Simple Ranged', '1d8', 'piercing', 80, 320,
     5, 'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bow'),
    ('crossbow-light-plus-two', 'Crossbow, light +2', 40000, 'gp', 'Ranged', 'Simple Ranged', '1d8', 'piercing', 80,
     320, 5, 'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare',
     'Bow'),
    ('crossbow-light-plus-three', 'Crossbow, light +3', 200000, 'gp', 'Ranged', 'Simple Ranged', '1d8', 'piercing', 80,
     320, 5, 'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary',
     'Bow'),
    ('dagger-plus-one', 'Dagger +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d4', 'piercing', 20, 60, 1,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Dagger'),
    ('dagger-plus-two', 'Dagger +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d4', 'piercing', 20, 60, 1,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Dagger'),
    ('dagger-plus-three', 'Dagger +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d4', 'piercing', 20, 60, 1,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Dagger'),

    ('dart-plus-one', 'Dart +1', 4000, 'gp', 'Ranged', 'Simple Ranged', '1d4', 'piercing', 20, 60, 0.25,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Thrown'),
    ('dart-plus-two', 'Dart +2', 40000, 'gp', 'Ranged', 'Simple Ranged', '1d4', 'piercing', 20, 60, 0.25,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Thrown'),
    ('dart-plus-three', 'Dart +3', 200000, 'gp', 'Ranged', 'Simple Ranged', '1d4', 'piercing', 20, 60, 0.25,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Thrown'),
    ('flail-plus-one', 'Flail +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bludgeon'),
    ('flail-plus-two', 'Flail +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bludgeon'),
    ('flail-plus-three', 'Flail +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bludgeon'),
    ('glaive-plus-one', 'Glaive +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Polearm'),
    ('glaive-plus-two', 'Glaive +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Polearm'),
    ('glaive-plus-three', 'Glaive +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Polearm'),
    ('greataxe-plus-one', 'Greataxe +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d12', 'slashing', 0, 0, 7,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Axe'),
    ('greataxe-plus-two', 'Greataxe +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d12', 'slashing', 0, 0, 7,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Axe'),
    ('greataxe-plus-three', 'Greataxe +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d12', 'slashing', 0, 0, 7,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Axe'),
    ('greatclub-plus-one', 'Greatclub +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d8', 'bludgeoning', 0, 0, 10,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bludgeon'),

    ('greatclub-plus-two', 'Greatclub +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d8', 'bludgeoning', 0, 0, 10,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bludgeon'),
    ('greatclub-plus-three', 'Greatclub +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d8', 'bludgeoning', 0, 0, 10,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bludgeon'),
    ('greatsword-plus-one', 'Greatsword +1', 4000, 'gp', 'Melee', 'Martial Melee', '2d6', 'slashing', 0, 0, 6,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Unknown'),
    ('greatsword-plus-two', 'Greatsword +2', 40000, 'gp', 'Melee', 'Martial Melee', '2d6', 'slashing', 0, 0, 6,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Unknown'),
    ('greatsword-plus-three', 'Greatsword +3', 200000, 'gp', 'Melee', 'Martial Melee', '2d6', 'slashing', 0, 0, 6,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Unknown'),
    ('halberd-plus-one', 'Halberd +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Polearm'),
    ('halberd-plus-two', 'Halberd +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Polearm'),
    ('halberd-plus-three', 'Halberd +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Polearm'),
    ('handaxe-plus-one', 'Handaxe +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d6', 'slashing', 20, 60, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Axe'),
    ('handaxe-plus-two', 'Handaxe +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d6', 'slashing', 20, 60, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Axe'),
    ('handaxe-plus-three', 'Handaxe +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d6', 'slashing', 20, 60, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Axe'),
    ('javelin-plus-one', 'Javelin +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d6', 'piercing', 30, 120, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Spear'),
    ('javelin-plus-two', 'Javelin +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d6', 'piercing', 30, 120, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Spear'),
    ('javelin-plus-three', 'Javelin +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d6', 'piercing', 30, 120, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Spear'),

    ('lance-plus-one', 'Lance +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d12', 'piercing', 0, 0, 6,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Polearm'),
    ('lance-plus-two', 'Lance +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d12', 'piercing', 0, 0, 6,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Polearm'),
    ('lance-plus-three', 'Lance +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d12', 'piercing', 0, 0, 6,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Polearm'),
    ('light-hammer-plus-one', 'Light hammer +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d4', 'bludgeoning', 20, 60, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Hammer'),
    ('light-hammer-plus-two', 'Light hammer +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d4', 'bludgeoning', 20, 60, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Hammer'),
    ('light-hammer-plus-three', 'Light hammer +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d4', 'bludgeoning', 20, 60,
     2, 'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Hammer'),
    ('longbow-plus-one', 'Longbow +1', 4000, 'gp', 'Ranged', 'Martial Ranged', '1d8', 'piercing', 150, 600, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bow'),
    ('longbow-plus-two', 'Longbow +2', 40000, 'gp', 'Ranged', 'Martial Ranged', '1d8', 'piercing', 150, 600, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bow'),
    ('longbow-plus-three', 'Longbow +3', 200000, 'gp', 'Ranged', 'Martial Ranged', '1d8', 'piercing', 150, 600, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bow'),
    ('longsword-plus-one', 'Longsword +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 3,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Sword'),
    ('longsword-plus-two', 'Longsword +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 3,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Sword'),
    ('longsword-plus-three', 'Longsword +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 3,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Sword'),
    ('mace-plus-one', 'Mace +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bludgeon'),
    ('mace-plus-two', 'Mace +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bludgeon'),
    ('mace-plus-three', 'Mace +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bludgeon'),
    ('maul-plus-one', 'Maul +1', 4000, 'gp', 'Melee', 'Martial Melee', '2d6', 'bludgeoning', 0, 0, 10,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bludgeon'),
    ('maul-plus-two', 'Maul +2', 40000, 'gp', 'Melee', 'Martial Melee', '2d6', 'bludgeoning', 0, 0, 10,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bludgeon'),
    ('maul-plus-three', 'Maul +3', 200000, 'gp', 'Melee', 'Martial Melee', '2d6', 'bludgeoning', 0, 0, 10,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bludgeon'),

    ('morningstar-plus-one', 'Morningstar +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 4,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Spiked'),
    ('morningstar-plus-two', 'Morningstar +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 4,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Spiked'),
    ('morningstar-plus-three', 'Morningstar +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 4,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Spiked'),
    ('net-plus-one', 'Net +1', 4000, 'gp', 'Ranged', 'Martial Ranged', '–', '–', 5, 15, 3,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Net'),
    ('net-plus-two', 'Net +2', 40000, 'gp', 'Ranged', 'Martial Ranged', '–', '–', 5, 15, 3,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Net'),
    ('net-plus-three', 'Net +3', 200000, 'gp', 'Ranged', 'Martial Ranged', '–', '–', 5, 15, 3,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Net'),
    ('pike-plus-one', 'Pike +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d10', 'piercing', 0, 0, 18,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Polearm'),
    ('pike-plus-two', 'Pike +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d10', 'piercing', 0, 0, 18,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Polearm'),
    ('pike-plus-three', 'Pike +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d10', 'piercing', 0, 0, 18,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Polearm'),
    ('quarterstaff-plus-one', 'Quarterstaff +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Staff'),
    ('quarterstaff-plus-two', 'Quarterstaff +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Staff'),
    ('quarterstaff-plus-three', 'Quarterstaff +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Staff'),
    ('rapier-plus-one', 'Rapier +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Sword'),
    ('rapier-plus-two', 'Rapier +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Sword'),
    ('rapier-plus-three', 'Rapier +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Sword'),
    ('scimitar-plus-one', 'Scimitar +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d6', 'slashing', 0, 0, 3,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Sword'),
    ('scimitar-plus-two', 'Scimitar +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d6', 'slashing', 0, 0, 3,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Sword'),
    ('scimitar-plus-three', 'Scimitar +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d6', 'slashing', 0, 0, 3,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Sword'),
    ('shortbow-plus-one', 'Shortbow +1', 4000, 'gp', 'Ranged', 'Simple Ranged', '1d6', 'piercing', 80, 320, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bow'),
    ('shortbow-plus-two', 'Shortbow +2', 40000, 'gp', 'Ranged', 'Simple Ranged', '1d6', 'piercing', 80, 320, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bow'),
    ('shortbow-plus-three', 'Shortbow +3', 200000, 'gp', 'Ranged', 'Simple Ranged', '1d6', 'piercing', 80, 320, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bow'),
    ('shortsword-plus-one', 'Shortsword +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d6', 'piercing', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Sword'),
    ('shortsword-plus-two', 'Shortsword +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d6', 'piercing', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Sword'),
    ('shortsword-plus-three', 'Shortsword +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d6', 'piercing', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Sword'),

    ('sickle-plus-one', 'Sickle +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d4', 'slashing', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Axe'),
    ('sickle-plus-two', 'Sickle +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d4', 'slashing', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Axe'),
    ('sickle-plus-three', 'Sickle +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d4', 'slashing', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Axe'),
    ('sling-plus-one', 'Sling +1', 4000, 'gp', 'Ranged', 'Simple Ranged', '1d4', 'bludgeoning', 30, 120, 0,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Thrown'),
    ('sling-plus-two', 'Sling +2', 40000, 'gp', 'Ranged', 'Simple Ranged', '1d4', 'bludgeoning', 30, 120, 0,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Thrown'),
    ('sling-plus-three', 'Sling +3', 200000, 'gp', 'Ranged', 'Simple Ranged', '1d4', 'bludgeoning', 30, 120, 0,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Thrown'),
    ('spear-plus-one', 'Spear +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d6', 'piercing', 20, 60, 3,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Spear'),
    ('spear-plus-two', 'Spear +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d6', 'piercing', 20, 60, 3,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Spear'),
    ('spear-plus-three', 'Spear +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d6', 'piercing', 20, 60, 3,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Spear'),
    ('trident-plus-one', 'Trident +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d6', 'piercing', 20, 60, 4,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Spear'),
    ('trident-plus-two', 'Trident +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d6', 'piercing', 20, 60, 4,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Spear'),
    ('trident-plus-three', 'Trident +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d6', 'piercing', 20, 60, 4,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Spear'),
    ('war-pick-plus-one', 'War pick +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Pick'),
    ('war-pick-plus-two', 'War pick +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Pick'),
    ('war-pick-plus-three', 'War pick +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Pick'),
    ('warhammer-plus-one', 'Warhammer +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Hammer'),
    ('warhammer-plus-two', 'Warhammer +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Hammer'),
    ('warhammer-plus-three', 'Warhammer +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Hammer'),
    ('whip-plus-one', 'Whip +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d4', 'slashing', 0, 0, 3,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Whip'),
    ('whip-plus-two', 'Whip +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d4', 'slashing', 0, 0, 3,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Whip'),
    ('whip-plus-three', 'Whip +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d4', 'slashing', 0, 0, 3,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Whip'),

    ('adamantine-battleaxe', 'Adamantine Battleaxe', 500, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 4,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Axe'),
    ('adamantine-greatsword', 'Adamantine Greatsword', 500, 'gp', 'Melee', 'Martial Melee', '2d6', 'slashing', 0, 0, 6,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Sword'),
    ('adamantine-longsword', 'Adamantine Longsword', 500, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 3,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Sword'),
    ('adamantine-maul', 'Adamantine Maul', 500, 'gp', 'Melee', 'Martial Melee', '2d6', 'bludgeoning', 0, 0, 10,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Hammer'),
    ('adamantine-morningstar', 'Adamantine Morningstar', 500, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 4,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Spiked'),
    ('adamantine-dagger', 'Adamantine Dagger', 500, 'gp', 'Melee', 'Simple Melee', '1d4', 'piercing', 20, 60, 1,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Dagger'),
    ('adamantine-glaive', 'Adamantine Glaive', 500, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Polearm'),
    ('adamantine-halberd', 'Adamantine Halberd', 500, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Polearm'),
    ('adamantine-mace', 'Adamantine Mace', 500, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Mace'),
    ('adamantine-war-pick', 'Adamantine War Pick', 500, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Pick'),
    ('adamantine-warhammer', 'Adamantine Warhammer', 500, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Hammer'),

]

GEAR_ROWS: list[tuple[str, str, int, str, float, str, int, bool, str, str]] = [
    ('adamantine-arrow', 'Adamantine Arrow', 100, 'gp', 0.05,
     'This arrow is made of adamantine, one of the hardest substances in existence. Whenever it hits an object, the hit is a Critical Hit.', 0, True, 'Uncommon', 'Ammunition'),

    ('adamantine-blowgun-needle', 'Adamantine Blowgun Needle', 100, 'gp', 0.01,
     'This blowgun made of adamantine, one of the hardest substances in existence. Whenever it hits an object, the hit is a Critical Hit.', 0, True, 'Uncommon', 'Ammunition'),

    ('adamantine-crossbow-bolt', 'Adamantine Crossbow Bolt', 100, 'gp', 0.1,
     'This bolt is tipped with adamantine, one of the hardest substances in existence. Whenever it hits an object, the hit is a Critical Hit.', 0, True, 'Uncommon', 'Ammunition'),

    ('adamantine-sling-bullet', 'Adamantine Sling Bullet', 100, 'gp', 0.1,
     'This sling bullet is forged from adamantine, one of the hardest substances in existence. Whenever it hits an object, the hit is a Critical Hit.', 0, True, 'Uncommon', 'Ammunition'),
]
