# Gemstone seed rows (srd_index, item_name, base_price, description)
GEM_ROWS: list[tuple[str, str, int, str]] = [
    ("azurite", "Azurite", 10, "opaque mottled deep blue. This gem drops on a \"1\" from a D12 roll"),
    ("banded-agate", "Banded agate", 10, "translucent striped brown, blue, white, or red. This gem drops on a \"2\" from a D12 roll"),
    ("blue-quartz", "Blue quartz", 10, "transparent pale blue. This gem drops on a \"3\" from a D12 roll"),
    ("eye-agate", "Eye agate", 10, "translucent circles of gray, white, brown, blue, or green. This gem drops on a \"4\" from a D12 roll"),
    ("hematite", "Hematite", 10, "opaque gray-black. This gem drops on a \"5\" from a D12 roll"),
    ("lapis-lazuli", "Lapis lazuli", 10, "opaque light and dark blue with yellow flecks. This gem drops on a \"6\" from a D12 roll"),
    ("malachite", "Malachite", 10, "opaque striated light and dark green. This gem drops on a \"7\" from a D12 roll"),
    ("moss-agate", "Moss agate", 10, "translucent pink or yellow-white with mossy gray or green markings. This gem drops on a \"8\" from a D12 roll"),
    ("obsidian", "Obsidian", 10, "opaque black. This gem drops on a \"9\" from a D12 roll"),
    ("rhodochrosite", "Rhodochrosite", 10, "opaque light pink. This gem drops on a \"10\" from a D12 roll"),
    ("tiger-eye", "Tiger eye", 10, "translucent brown with golden center. This gem drops on a \"11\" from a D12 roll"),
    ("turquoise", "Turquoise", 10, "opaque light blue-green. This gem drops on a \"12\" from a D12 roll"),
    ("bloodstone", "Bloodstone", 50, "opaque dark gray with red flecks. This gem drops on a \"1\" from a D10 roll"),
    ("carnelian", "Carnelian", 50, "opaque orange to red-brown. This gem drops on a \"2\" from a D10 roll"),
    ("chalcedony", "Chalcedony", 50, "opaque white. This gem drops on a \"3\" from a D10 roll"),
    ("chrysoprase", "Chrysoprase", 50, "translucent green. This gem drops on a \"4\" from a D10 roll"),
    ("citrine", "Citrine", 50, "transparent pale yellow-brown. This gem drops on a \"5\" from a D10 roll"),
    ("jasper", "Jasper", 50, "opaque blue, black, or brown. This gem drops on a \"6\" from a D10 roll"),
    ("moonstone", "Moonstone", 50, "translucent white with pale blue glow. This gem drops on a \"7\" from a D10 roll"),
    ("onyx", "Onyx", 50, "opaque bands of black and white, or pure black or white. This gem drops on a \"8\" from a D10 roll"),
    ("quartz", "Quartz", 50, "transparent white, smoky gray, or yellow. This gem drops on a \"9\" from a D10 roll"),
    ("sardonyx", "Sardonyx", 50, "opaque bands of red and white. This gem drops on a \"10\" from a D10 roll"),
    ("star-rose-quartz", "Star rose quartz", 50, "translucent rosy stone with white star-shaped center. This gem drops on a \"11\" from a D10 roll"),
    ("zircon", "Zircon", 50, "transparent pale blue-green. This gem drops on a \"12\" from a D10 roll"),
    ("amber", "Amber", 100, "watery gold to rich gold. This gem drops on a \"1\" from a D8 roll"),
    ("amethyst", "Amethyst", 100, "deep purple. This gem drops on a \"2\" from a D8 roll"),
    ("chrysoberyl", "Chrysoberyl", 100, "yellow-green to pale green. This gem drops on a \"3\" from a D8 roll"),
    ("coral", "Coral", 100, "crimson. This gem drops on a \"4\" from a D8 roll"),
    ("garnet", "Garnet", 100, "red, brown-green, or violet. This gem drops on a \"5\" from a D8 roll"),
    ("jade", "Jade", 100, "light green, deep green or white. This gem drops on a \"6\" from a D8 roll"),
    ("jet", "Jet", 100, "deep black. This gem drops on a \"7\" from a D8 roll"),
    ("pearl", "Pearl", 100, "lustrous white, yellow or pink. This gem drops on a \"8\" from a D8 roll"),
    ("spinel", "Spinel", 100, "red, red-brown, or deep green. This gem drops on a \"9\" from a D8 roll"),
    ("tourmaline", "Tourmaline", 100, "pale green, blue, brown or red. This gem drops on a \"10\" from a D8 roll"),
    ("alexandrite", "Alexandrite", 500, "transparent dark green. This gem drops on a \"1\" from a D6 roll"),
    ("aquamarine", "Aquamarine", 500, "transparent pale blue-green. This gem drops on a \"2\" from a D6 roll"),
    ("black-pearl", "Black pearl", 500, "opaque pure black. This gem drops on a \"3\" from a D6 roll"),
    ("blue-spinel", "Blue spinel", 500, "transparent deep blue. This gem drops on a \"4\" from a D6 roll"),
    ("peridot", "Peridot", 500, "transparent rich olive green. This gem drops on a \"5\" from a D6 roll"),
    ("topaz", "Topaz", 500, "transparent golden yellow. This gem drops on a \"6\" from a D6 roll"),
    ("black-opal", "Black opal", 1000, "translucent dark green with black mottling and golden flecks. This gem drops on a \"1\" from a D8 roll"),
    ("blue-sapphire", "Blue sapphire", 1000, "transparent blue-white to medium blue. This gem drops on a \"2\" from a D8 roll"),
    ("emerald", "Emerald", 1000, "transparent deep bright green. This gem drops on a \"3\" from a D8 roll"),
    ("fire-opal", "Fire opal", 1000, "translucent fiery red. This gem drops on a \"4\" from a D8 roll"),
    ("opal", "Opal", 1000, "translucent pale blue with green and golden mottling. This gem drops on a \"5\" from a D8 roll"),
    ("star-ruby", "Star ruby", 1000, "translucent ruby with white star-shaped center. This gem drops on a \"6\" from a D8 roll"),
    ("star-sapphire", "Star sapphire", 1000, "translucent blue sapphire with white star-shaped center. This gem drops on a \"7\" from a D8 roll"),
    ("yellow-sapphire", "Yellow sapphire", 1000, "transparent fiery yellow or yellow-green. This gem drops on a \"8\" from a D8 roll"),
    ("black-sapphire", "Black sapphire", 5000, "translucent lustrous black with glowing highlights. This gem drops on a \"1\" from a D4 roll"),
    ("diamond", "Diamond", 5000, "transparent blue-white, canary, pink, brown, or blue. This gem drops on a \"2\" from a D4 roll"),
    ("jacinth", "Jacinth", 5000, "transparent fiery orange. This gem drops on a \"3\" from a D4 roll"),
    ("ruby", "Ruby", 5000, "transparent clear red to deep crimson. This gem drops on a \"4\" from a D4 roll"),
]
