# Armor seed rows with armour_category included
ARMOR_ROWS: list[tuple[str, str, int, str, int, bool, int, int, bool, int, str, int, bool, str, str]] = [
    ('leather-armor-plus-one', 'Leather Armor +1', 4000, 'gp', 11, True, 0, 0, False, 10, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Light'),
    ('padded-armor-plus-one', 'Padded Armor +1', 4000, 'gp', 11, True, 0, 0, True, 8, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Light'),
    ('shield-plus-one', 'Shield +1', 4000, 'gp', 2, False, 0, 0, False, 6, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Shield'),
    ('studded-leather-armor-plus-one', 'Studded Leather Armor +1', 4000, 'gp', 12, True, 0, 0, True, 13, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('leather-armor-plus-two', 'Leather Armor +2', 40000, 'gp', 11, True, 0, 0, False, 10, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Light'),
    ('padded-armor-plus-two', 'Padded Armor +2', 40000, 'gp', 11, True, 0, 0, True, 8, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Light'),
    ('shield-plus-two', 'Shield +2', 40000, 'gp', 2, False, 0, 0, False, 6, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Shield'),
    ('studded-leather-armor-plus-two', 'Studded Leather Armor +2', 40000, 'gp', 12, True, 0, 0, False, 13, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('leather-armor-plus-three', 'Leather Armor +3', 200000, 'gp', 11, True, 0, 0, False, 10, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Light'),
    ('padded-armor-plus-three', 'Padded Armor +3', 200000, 'gp', 11, True, 0, 0, True, 8, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Light'),
    ('shield-plus-three', 'Shield +3', 200000, 'gp', 2, False, 0, 0, False, 6, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Shield'),
    ('studded-leather-armor-plus-three', 'Studded Leather Armor +3', 200000, 'gp', 12, True, 0, 0, False, 13, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('breastplate-plus-one', 'Breastplate +1', 4000, 'gp', 14, True, 2, 0, False, 20, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('chain-mail-plus-one', 'Chain Mail +1', 4000, 'gp', 16, False, 0, 13, True, 55, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Heavy'),
    ('chain-shirt-plus-one', 'Chain Shirt +1', 4000, 'gp', 13, True, 2, 0, False, 20, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('half-plate-armor-plus-one', 'Half Plate Armor +1', 4000, 'gp', 15, True, 2, 0, True, 40, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('hide-armor-plus-one', 'Hide Armor +1', 4000, 'gp', 12, True, 2, 0, False, 12, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('plate-armor-plus-one', 'Plate Armor +1', 4000, 'gp', 18, False, 0, 15, True, 65, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Heavy'),
    ('ring-mail-plus-one', 'Ring Mail +1', 4000, 'gp', 14, False, 0, 0, True, 40, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Heavy'),
    ('scale-mail-plus-one', 'Scale Mail +1', 4000, 'gp', 14, True, 2, 0, True, 45, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('splint-armor-plus-one', 'Splint Armor +1', 4000, 'gp', 17, False, 0, 15, True, 60, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Heavy'),
    ('breastplate-plus-two', 'Breastplate +2', 40000, 'gp', 14, True, 2, 0, False, 20, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('chain-mail-plus-two', 'Chain Mail +2', 40000, 'gp', 16, False, 0, 13, True, 55, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Heavy'),
    ('chain-shirt-plus-two', 'Chain Shirt +2', 40000, 'gp', 13, True, 2, 0, False, 20, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('half-plate-armor-plus-two', 'Half Plate Armor +2', 40000, 'gp', 15, True, 2, 0, True, 40, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('hide-armor-plus-two', 'Hide Armor +2', 40000, 'gp', 12, True, 2, 0, False, 12, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('plate-armor-plus-two', 'Plate Armor +2', 40000, 'gp', 18, False, 0, 15, True, 65, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Heavy'),
    ('ring-mail-plus-two', 'Ring Mail +2', 40000, 'gp', 14, False, 0, 0, True, 40, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Heavy'),
    ('scale-mail-plus-two', 'Scale Mail +2', 40000, 'gp', 14, True, 2, 0, True, 45, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('splint-armor-plus-two', 'Splint Armor +2', 40000, 'gp', 17, False, 0, 15, True, 60, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Heavy'),
    ('breastplate-plus-three', 'Breastplate +3', 200000, 'gp', 14, True, 2, 0, False, 20, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('chain-mail-plus-three', 'Chain Mail +3', 200000, 'gp', 16, False, 0, 13, True, 55, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Heavy'),
    ('chain-shirt-plus-three', 'Chain Shirt +3', 200000, 'gp', 13, True, 2, 0, False, 20, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('half-plate-armor-plus-three', 'Half Plate Armor +3', 200000, 'gp', 15, True, 2, 0, True, 40, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('hide-armor-plus-three', 'Hide Armor +3', 200000, 'gp', 12, True, 2, 0, False, 12, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('plate-armor-plus-three', 'Plate Armor +3', 200000, 'gp', 18, False, 0, 15, True, 65, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Heavy'),
    ('ring-mail-plus-three', 'Ring Mail +3', 200000, 'gp', 14, False, 0, 0, True, 40, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Heavy'),
    ('scale-mail-plus-three', 'Scale Mail +3', 200000, 'gp', 14, True, 2, 0, True, 45, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('splint-armor-plus-three', 'Splint Armor +3', 200000, 'gp', 17, False, 0, 15, True, 60, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Heavy'),
    ('adamantine-breastplate', 'Adamantine Breastplate', 400, 'gp', 14, True, 2, 0, False, 20, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Medium'),
    ('adamantine-chain-mail', 'Adamantine Chain Mail', 400, 'gp', 16, False, 0, 13, True, 55, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Heavy'),
    ('adamantine-chain-shirt', 'Adamantine Chain Shirt', 400, 'gp', 13, True, 2, 0, False, 20, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Medium'),
    ('adamantine-half-plate-armor', 'Adamantine Half Plate Armor', 400, 'gp', 15, True, 2, 0, True, 40, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Medium'),
    ('adamantine-plate-armor', 'Adamantine Plate Armor', 400, 'gp', 18, False, 0, 15, True, 65, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Heavy'),
    ('adamantine-ring-mail', 'Adamantine Ring Mail', 400, 'gp', 14, False, 0, 0, True, 40, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Heavy'),
    ('adamantine-scale-mail', 'Adamantine Scale Mail', 400, 'gp', 14, True, 2, 0, True, 45, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Medium'),
    ('adamantine-splint-armor', 'Adamantine Splint Armor', 400, 'gp', 17, False, 0, 15, True, 60, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Heavy'),
]

WEAPON_ROWS: list[tuple[str, str, int, str, str, str, str, str, int, int, float, str, int, bool, str, str]] = [

    ('battleaxe-plus-one', 'Battleaxe +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 4,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Axe'),
    ('battleaxe-plus-two', 'Battleaxe +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 4,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Axe'),
    ('battleaxe-plus-three', 'Battleaxe +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 4,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Axe'),
    ('blowgun-plus-one', 'Blowgun +1', 4000, 'gp', 'Ranged', 'Martial Ranged', '1', 'piercing', 25, 100, 1,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Blowgun'),
    ('blowgun-plus-two', 'Blowgun +2', 40000, 'gp', 'Ranged', 'Martial Ranged', '1', 'piercing', 25, 100, 1,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Blowgun'),
    ('blowgun-plus-three', 'Blowgun +3', 200000, 'gp', 'Ranged', 'Martial Ranged', '1', 'piercing', 25, 100, 1,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Blowgun'),
    ('club-plus-one', 'Club +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d4', 'bludgeoning', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bludgeon'),
    ('club-plus-two', 'Club +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d4', 'bludgeoning', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bludgeon'),
    ('club-plus-three', 'Club +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d4', 'bludgeoning', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bludgeon'),

    ('crossbow-hand-plus-one', 'Crossbow, hand +1', 4000, 'gp', 'Ranged', 'Martial Ranged', '1d6', 'piercing', 30, 120,
     3, 'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bow'),
    ('crossbow-hand-plus-two', 'Crossbow, hand +2', 40000, 'gp', 'Ranged', 'Martial Ranged', '1d6', 'piercing', 30, 120,
     3, 'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bow'),
    ('crossbow-hand-plus-three', 'Crossbow, hand +3', 200000, 'gp', 'Ranged', 'Martial Ranged', '1d6', 'piercing', 30,
     120, 3, 'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary',
     'Bow'),
    ('crossbow-heavy-plus-one', 'Crossbow, heavy +1', 4000, 'gp', 'Ranged', 'Martial Ranged', '1d10', 'piercing', 100,
     400, 18, 'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bow'),
    ('crossbow-heavy-plus-two', 'Crossbow, heavy +2', 40000, 'gp', 'Ranged', 'Martial Ranged', '1d10', 'piercing', 100,
     400, 18, 'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare',
     'Bow'),
    ('crossbow-heavy-plus-three', 'Crossbow, heavy +3', 200000, 'gp', 'Ranged', 'Martial Ranged', '1d10', 'piercing',
     100, 400, 18, 'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary',
     'Bow'),
    ('crossbow-light-plus-one', 'Crossbow, light +1', 4000, 'gp', 'Ranged', 'Simple Ranged', '1d8', 'piercing', 80, 320,
     5, 'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bow'),
    ('crossbow-light-plus-two', 'Crossbow, light +2', 40000, 'gp', 'Ranged', 'Simple Ranged', '1d8', 'piercing', 80,
     320, 5, 'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare',
     'Bow'),
    ('crossbow-light-plus-three', 'Crossbow, light +3', 200000, 'gp', 'Ranged', 'Simple Ranged', '1d8', 'piercing', 80,
     320, 5, 'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary',
     'Bow'),
    ('dagger-plus-one', 'Dagger +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d4', 'piercing', 20, 60, 1,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Dagger'),
    ('dagger-plus-two', 'Dagger +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d4', 'piercing', 20, 60, 1,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Dagger'),
    ('dagger-plus-three', 'Dagger +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d4', 'piercing', 20, 60, 1,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Dagger'),

    ('dart-plus-one', 'Dart +1', 4000, 'gp', 'Ranged', 'Simple Ranged', '1d4', 'piercing', 20, 60, 0.25,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Thrown'),
    ('dart-plus-two', 'Dart +2', 40000, 'gp', 'Ranged', 'Simple Ranged', '1d4', 'piercing', 20, 60, 0.25,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Thrown'),
    ('dart-plus-three', 'Dart +3', 200000, 'gp', 'Ranged', 'Simple Ranged', '1d4', 'piercing', 20, 60, 0.25,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Thrown'),
    ('flail-plus-one', 'Flail +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bludgeon'),
    ('flail-plus-two', 'Flail +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bludgeon'),
    ('flail-plus-three', 'Flail +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bludgeon'),
    ('glaive-plus-one', 'Glaive +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Polearm'),
    ('glaive-plus-two', 'Glaive +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Polearm'),
    ('glaive-plus-three', 'Glaive +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Polearm'),
    ('greataxe-plus-one', 'Greataxe +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d12', 'slashing', 0, 0, 7,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Axe'),
    ('greataxe-plus-two', 'Greataxe +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d12', 'slashing', 0, 0, 7,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Axe'),
    ('greataxe-plus-three', 'Greataxe +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d12', 'slashing', 0, 0, 7,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Axe'),
    ('greatclub-plus-one', 'Greatclub +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d8', 'bludgeoning', 0, 0, 10,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bludgeon'),

    ('greatclub-plus-two', 'Greatclub +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d8', 'bludgeoning', 0, 0, 10,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bludgeon'),
    ('greatclub-plus-three', 'Greatclub +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d8', 'bludgeoning', 0, 0, 10,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bludgeon'),
    ('greatsword-plus-one', 'Greatsword +1', 4000, 'gp', 'Melee', 'Martial Melee', '2d6', 'slashing', 0, 0, 6,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Unknown'),
    ('greatsword-plus-two', 'Greatsword +2', 40000, 'gp', 'Melee', 'Martial Melee', '2d6', 'slashing', 0, 0, 6,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Unknown'),
    ('greatsword-plus-three', 'Greatsword +3', 200000, 'gp', 'Melee', 'Martial Melee', '2d6', 'slashing', 0, 0, 6,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Unknown'),
    ('halberd-plus-one', 'Halberd +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Polearm'),
    ('halberd-plus-two', 'Halberd +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Polearm'),
    ('halberd-plus-three', 'Halberd +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Polearm'),
    ('handaxe-plus-one', 'Handaxe +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d6', 'slashing', 20, 60, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Axe'),
    ('handaxe-plus-two', 'Handaxe +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d6', 'slashing', 20, 60, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Axe'),
    ('handaxe-plus-three', 'Handaxe +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d6', 'slashing', 20, 60, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Axe'),
    ('javelin-plus-one', 'Javelin +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d6', 'piercing', 30, 120, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Spear'),
    ('javelin-plus-two', 'Javelin +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d6', 'piercing', 30, 120, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Spear'),
    ('javelin-plus-three', 'Javelin +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d6', 'piercing', 30, 120, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Spear'),

    ('lance-plus-one', 'Lance +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d12', 'piercing', 0, 0, 6,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Polearm'),
    ('lance-plus-two', 'Lance +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d12', 'piercing', 0, 0, 6,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Polearm'),
    ('lance-plus-three', 'Lance +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d12', 'piercing', 0, 0, 6,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Polearm'),
    ('light-hammer-plus-one', 'Light hammer +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d4', 'bludgeoning', 20, 60, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Hammer'),
    ('light-hammer-plus-two', 'Light hammer +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d4', 'bludgeoning', 20, 60, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Hammer'),
    ('light-hammer-plus-three', 'Light hammer +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d4', 'bludgeoning', 20, 60,
     2, 'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Hammer'),
    ('longbow-plus-one', 'Longbow +1', 4000, 'gp', 'Ranged', 'Martial Ranged', '1d8', 'piercing', 150, 600, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bow'),
    ('longbow-plus-two', 'Longbow +2', 40000, 'gp', 'Ranged', 'Martial Ranged', '1d8', 'piercing', 150, 600, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bow'),
    ('longbow-plus-three', 'Longbow +3', 200000, 'gp', 'Ranged', 'Martial Ranged', '1d8', 'piercing', 150, 600, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bow'),
    ('longsword-plus-one', 'Longsword +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 3,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Sword'),
    ('longsword-plus-two', 'Longsword +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 3,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Sword'),
    ('longsword-plus-three', 'Longsword +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 3,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Sword'),
    ('mace-plus-one', 'Mace +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bludgeon'),
    ('mace-plus-two', 'Mace +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bludgeon'),
    ('mace-plus-three', 'Mace +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bludgeon'),
    ('maul-plus-one', 'Maul +1', 4000, 'gp', 'Melee', 'Martial Melee', '2d6', 'bludgeoning', 0, 0, 10,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bludgeon'),
    ('maul-plus-two', 'Maul +2', 40000, 'gp', 'Melee', 'Martial Melee', '2d6', 'bludgeoning', 0, 0, 10,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bludgeon'),
    ('maul-plus-three', 'Maul +3', 200000, 'gp', 'Melee', 'Martial Melee', '2d6', 'bludgeoning', 0, 0, 10,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bludgeon'),

    ('morningstar-plus-one', 'Morningstar +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 4,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Spiked'),
    ('morningstar-plus-two', 'Morningstar +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 4,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Spiked'),
    ('morningstar-plus-three', 'Morningstar +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 4,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Spiked'),
    ('net-plus-one', 'Net +1', 4000, 'gp', 'Ranged', 'Martial Ranged', '–', '–', 5, 15, 3,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Net'),
    ('net-plus-two', 'Net +2', 40000, 'gp', 'Ranged', 'Martial Ranged', '–', '–', 5, 15, 3,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Net'),
    ('net-plus-three', 'Net +3', 200000, 'gp', 'Ranged', 'Martial Ranged', '–', '–', 5, 15, 3,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Net'),
    ('pike-plus-one', 'Pike +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d10', 'piercing', 0, 0, 18,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Polearm'),
    ('pike-plus-two', 'Pike +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d10', 'piercing', 0, 0, 18,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Polearm'),
    ('pike-plus-three', 'Pike +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d10', 'piercing', 0, 0, 18,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Polearm'),
    ('quarterstaff-plus-one', 'Quarterstaff +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Staff'),
    ('quarterstaff-plus-two', 'Quarterstaff +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Staff'),
    ('quarterstaff-plus-three', 'Quarterstaff +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Staff'),
    ('rapier-plus-one', 'Rapier +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Sword'),
    ('rapier-plus-two', 'Rapier +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Sword'),
    ('rapier-plus-three', 'Rapier +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Sword'),
    ('scimitar-plus-one', 'Scimitar +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d6', 'slashing', 0, 0, 3,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Sword'),
    ('scimitar-plus-two', 'Scimitar +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d6', 'slashing', 0, 0, 3,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Sword'),
    ('scimitar-plus-three', 'Scimitar +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d6', 'slashing', 0, 0, 3,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Sword'),
    ('shortbow-plus-one', 'Shortbow +1', 4000, 'gp', 'Ranged', 'Simple Ranged', '1d6', 'piercing', 80, 320, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Bow'),
    ('shortbow-plus-two', 'Shortbow +2', 40000, 'gp', 'Ranged', 'Simple Ranged', '1d6', 'piercing', 80, 320, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Bow'),
    ('shortbow-plus-three', 'Shortbow +3', 200000, 'gp', 'Ranged', 'Simple Ranged', '1d6', 'piercing', 80, 320, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Bow'),
    ('shortsword-plus-one', 'Shortsword +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d6', 'piercing', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Sword'),
    ('shortsword-plus-two', 'Shortsword +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d6', 'piercing', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Sword'),
    ('shortsword-plus-three', 'Shortsword +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d6', 'piercing', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Sword'),

    ('sickle-plus-one', 'Sickle +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d4', 'slashing', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Axe'),
    ('sickle-plus-two', 'Sickle +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d4', 'slashing', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Axe'),
    ('sickle-plus-three', 'Sickle +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d4', 'slashing', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Axe'),
    ('sling-plus-one', 'Sling +1', 4000, 'gp', 'Ranged', 'Simple Ranged', '1d4', 'bludgeoning', 30, 120, 0,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Thrown'),
    ('sling-plus-two', 'Sling +2', 40000, 'gp', 'Ranged', 'Simple Ranged', '1d4', 'bludgeoning', 30, 120, 0,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Thrown'),
    ('sling-plus-three', 'Sling +3', 200000, 'gp', 'Ranged', 'Simple Ranged', '1d4', 'bludgeoning', 30, 120, 0,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Thrown'),
    ('spear-plus-one', 'Spear +1', 4000, 'gp', 'Melee', 'Simple Melee', '1d6', 'piercing', 20, 60, 3,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Spear'),
    ('spear-plus-two', 'Spear +2', 40000, 'gp', 'Melee', 'Simple Melee', '1d6', 'piercing', 20, 60, 3,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Spear'),
    ('spear-plus-three', 'Spear +3', 200000, 'gp', 'Melee', 'Simple Melee', '1d6', 'piercing', 20, 60, 3,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Spear'),
    ('trident-plus-one', 'Trident +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d6', 'piercing', 20, 60, 4,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Spear'),
    ('trident-plus-two', 'Trident +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d6', 'piercing', 20, 60, 4,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Spear'),
    ('trident-plus-three', 'Trident +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d6', 'piercing', 20, 60, 4,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Spear'),
    ('war-pick-plus-one', 'War pick +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Pick'),
    ('war-pick-plus-two', 'War pick +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Pick'),
    ('war-pick-plus-three', 'War pick +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Pick'),
    ('warhammer-plus-one', 'Warhammer +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Hammer'),
    ('warhammer-plus-two', 'Warhammer +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Hammer'),
    ('warhammer-plus-three', 'Warhammer +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Hammer'),
    ('whip-plus-one', 'Whip +1', 4000, 'gp', 'Melee', 'Martial Melee', '1d4', 'slashing', 0, 0, 3,
     'You have a +1 bonus to attack and damage rolls made with this magic weapon.', 1, True, 'Rare', 'Whip'),
    ('whip-plus-two', 'Whip +2', 40000, 'gp', 'Melee', 'Martial Melee', '1d4', 'slashing', 0, 0, 3,
     'You have a +2 bonus to attack and damage rolls made with this magic weapon.', 2, True, 'Very Rare', 'Whip'),
    ('whip-plus-three', 'Whip +3', 200000, 'gp', 'Melee', 'Martial Melee', '1d4', 'slashing', 0, 0, 3,
     'You have a +3 bonus to attack and damage rolls made with this magic weapon.', 3, True, 'Legendary', 'Whip'),

    ('adamantine-battleaxe', 'Adamantine Battleaxe', 500, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 4,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Axe'),
    ('adamantine-greatsword', 'Adamantine Greatsword', 500, 'gp', 'Melee', 'Martial Melee', '2d6', 'slashing', 0, 0, 6,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Sword'),
    ('adamantine-longsword', 'Adamantine Longsword', 500, 'gp', 'Melee', 'Martial Melee', '1d8', 'slashing', 0, 0, 3,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Sword'),
    ('adamantine-maul', 'Adamantine Maul', 500, 'gp', 'Melee', 'Martial Melee', '2d6', 'bludgeoning', 0, 0, 10,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Hammer'),
    ('adamantine-morningstar', 'Adamantine Morningstar', 500, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 4,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Spiked'),
    ('adamantine-dagger', 'Adamantine Dagger', 500, 'gp', 'Melee', 'Simple Melee', '1d4', 'piercing', 20, 60, 1,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Dagger'),
    ('adamantine-glaive', 'Adamantine Glaive', 500, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Polearm'),
    ('adamantine-halberd', 'Adamantine Halberd', 500, 'gp', 'Melee', 'Martial Melee', '1d10', 'slashing', 0, 0, 6,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Polearm'),
    ('adamantine-mace', 'Adamantine Mace', 500, 'gp', 'Melee', 'Simple Melee', '1d6', 'bludgeoning', 0, 0, 4,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Mace'),
    ('adamantine-war-pick', 'Adamantine War Pick', 500, 'gp', 'Melee', 'Martial Melee', '1d8', 'piercing', 0, 0, 2,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Pick'),
    ('adamantine-warhammer', 'Adamantine Warhammer', 500, 'gp', 'Melee', 'Martial Melee', '1d8', 'bludgeoning', 0, 0, 2,
     'This magic weapon’s strikes always count as critical hits.', 0, True, 'Uncommon', 'Hammer'),

]

GEAR_ROWS: list[tuple[str, str, int, str, float, str, int, bool, str, str]] = [

    #ammo
    ('adamantine-arrow', 'Adamantine Arrow', 400, 'gp', 0.05,
     'This arrow is made of adamantine, one of the hardest substances in existence. Whenever it hits an object, the hit is a Critical Hit. This item is consumed on use.', 0, True, 'Uncommon', 'Ammunition'),

    ('adamantine-blowgun-needle', 'Adamantine Blowgun Needle', 400, 'gp', 0.01,
     'This blowgun made of adamantine, one of the hardest substances in existence. Whenever it hits an object, the hit is a Critical Hit. This item is consumed on use.', 0, True, 'Uncommon', 'Ammunition'),

    ('adamantine-crossbow-bolt', 'Adamantine Crossbow Bolt', 400, 'gp', 0.1,
     'This bolt is tipped with adamantine, one of the hardest substances in existence. Whenever it hits an object, the hit is a Critical Hit. This item is consumed on use.', 0, True, 'Uncommon', 'Ammunition'),

    ('adamantine-sling-bullet', 'Adamantine Sling Bullet', 400, 'gp', 0.1,
     'This sling bullet is forged from adamantine, one of the hardest substances in existence. Whenever it hits an object, the hit is a Critical Hit. This item is consumed on use.', 0, True, 'Uncommon', 'Ammunition'),

    # potions
    ('potion-of-healing', 'Potion of Healing', 100, 'gp', 0.1,
     'The red liquid glimmers when agitated. You regain 2d4+2 Hit Points when you drink this potion. This item is consumed when used.',
     0, True, 'Common', 'Potion'),

    ('greater-potion-of-healing', 'Greater Potion of Healing', 400, 'gp', 0.1,
     'You regain 4d4+4 Hit Points when you drink this potion. The red liquid glimmers when agitated. This item is consumed when used.',
     0, True, 'Uncommon', 'Potion'),

    ('superior-potion-of-healing', 'Superior Potion of Healing', 4000, 'gp', 0.1,
     'You regain 8d4+8 Hit Points when you drink this potion. The red liquid glimmers when agitated. This item is consumed when used.',
     0, True, 'Rare', 'Potion'),

    ('supreme-potion-of-healing', 'Supreme Potion of Healing', 40000, 'gp', 0.1,
     'You regain 10d4+20 Hit Points when you drink this potion. The red liquid glimmers when agitated. This item is consumed when used.',
     0, True, 'Very Rare', 'Potion'),

    ('potion-of-animal-friendship', 'Potion of Animal Friendship', 400, 'gp', 0.1,
     'When you drink this potion, you can cast the level 3 version of the *Animal Friendship* spell (save DC 13). Agitating this potions muddy liquid brings little bits into view; a fish scale, a hummingbird feather, a cat claw or a squirrel hair. This item is consumed when used.',
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-clairvoyance', 'Potion of Animal Friendship', 40000, 'gp', 0.1,
     'When you drink this potion, you gain the effect of the *Clairvoyance* spell (no Concentration required). An eyeball bobs in this potions yellowish liquid but vanishes when the potion is opened. This item is consumed when used.',
     0, True, 'Rare', 'Potion'),

    ('potion-of-climbing', 'Potion of Climbing', 40000, 'gp', 0.1,
     'When you drink this potion, you gain a Climb Speed equal to your Speed for 1 hour. During this time you have Advantage on Strength (Athletics) checks to climb. This potion is separated into brown, silver and gray layers resembling bands of stone Shaking the bottle fails to mix the colours. This item is consumed when used.',
     0, True, 'Rare', 'Potion'),

    ('potion-of-comprehension', 'Potion of Comprehension', 400, 'gp', 0.1,
     "When you drink this potion, you gain the effect of the *Comprehend Languages* spell for 1 hour. This potion's liquid is a clear concoction with bits of salt and soot swirling in it. This item is consumed when used.",
     0, True, 'Common', 'Potion'),

    ('potion-of-diminution', 'Potion of Diminution', 40000, 'gp', 0.1,
     "When you drink this potion, you gain the 'reduce' effect of the *Enlarge/Reduce* spell for 1d4 hours (no Concentration required). The red in the potion's liquid continuously contracts to a tiny bead and then expands to color the clear liquid around it. Shaking the bottle fails interrupt the process.",
     0, True, 'Rare', 'Potion'),

    ('potion-of-growth', 'Potion of Growth', 4000, 'gp', 0.1,
     "When you drink this potion, you gain the 'enlarge' effect of the *Enlarge/Reduce* spell for 1d4 hours (no Concentration required). The red in the potion's liquid continuously expands from a tiny bead and then contracts. Shaking the bottle fails interrupt the process.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-fire-breath', 'Potion of Fire Breath', 4000, 'gp', 0.1,
     "After drinking this potion, you can take a Bonus Action to exhale fire at a target within 30 feet of yourself. The target makes a DC 13 Dexterity saving throw, taking 4d6 Fire damage on a failed save or half as much damage on a successful one. This potion's orange liquid flickers, and smoke fills the top of the container and wafts out whenever it is opened.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-gaseous-form', 'Potion of Gaseous Form', 4000, 'gp', 0.1,
     "When you drink this potion, you gain the effect of the *Gaseous Form* spell for 1 hour (no Concentration required) or until you end the effect as a Bonus Action."
     "This potion's container seems to hold fog that moves and pours like water.",
     0, True, 'Rare', 'Potion'),

    ('potion-of-hill-giant-strength', 'Potion of Hill Giant Strength', 400, 'gp', 0.1,
     "When you drink this potion, your Strength score increases to 21 for 1 hour. This potion has no effect on you if your Strength is equal to or greater than 21."
     "This potion's transparent liquid has floating in it a silver light resembling a giant's finger nail.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-frost-giant-strength', 'Potion of Frost Giant Strength', 400, 'gp', 0.1,
     "When you drink this potion, your Strength score increases to 23 for 1 hour. This potion has no effect on you if your Strength is equal to or greater than 23."
     "This potion's transparent liquid has floating in it a silver light resembling a giant's finger nail.",
     0, True, 'Rare', 'Potion'),

    ('potion-of-fire-giant-strength', 'Potion of Fire Giant Strength', 4000, 'gp', 0.1,
     "When you drink this potion, your Strength score increases to 25 for 1 hour. This potion has no effect on you if your Strength is equal to or greater than 25."
     "This potion's transparent liquid has floating in it a silver light resembling a giant's finger nail.",
     0, True, 'Rare', 'Potion'),

    ('potion-of-cloud-giant-strength', 'Potion of Cloud Giant Strength', 400000, 'gp', 0.1,
     "When you drink this potion, your Strength score increases to 27 for 1 hour. This potion has no effect on you if your Strength is equal to or greater than 27."
     "This potion's transparent liquid has floating in it a silver light resembling a giant's finger nail.",
     0, True, 'Very Rare', 'Potion'),

    ('potion-of-storm-giant-strength', 'Potion of Storm Giant Strength', 200000, 'gp', 0.1,
     "When you drink this potion, your Strength score increases to 29 for 1 hour. This potion has no effect on you if your Strength is equal to or greater than 29."
     "This potion's transparent liquid has floating in it a silver light resembling a giant's finger nail.",
     0, True, 'Legendary', 'Potion'),

    ('potion-of-greater-invisibility', 'Potion of Greater Invisibility', 40000, 'gp', 0.1,
     "This potion's container looks empty but feels as though it holds liquid."
     "When you drink this potion you have the Invisible condition for 1 hour.",
     0, True, 'Very Rare', 'Potion'),

    ('potion-of-heroism', 'Potion of Heroism', 40000, 'gp', 0.1,
     "When you drink this potion, you gain 10 Temporary Hit Points that last for 1 hour. You are also under the effect of the *Bless* spell for the same duration."
     "This potion's blue liquid bubbles and streams as if boiling.",
     0, True, 'Rare', 'Potion'),

    ('potion-of-invisibility', 'Potion of Invisibility', 4000, 'gp', 0.1,
     "This potion's container looks empty but feels as though it holds liquid."
     "When you drink this potion you have the Invisible condition for 1 hour. The effect ends early if you make an attack roll, deal damage or cast a spell.",
     0, True, 'Rare', 'Potion'),

    ('potion-of-invulnerability', 'Potion of Invulnerability', 4000, 'gp', 0.1,
     "For 1 minute after you drink this potion, you have Resistance to all damage."
     "This potion's syrupy liquid looks like liquified iron.",
     0, True, 'Very Rare', 'Potion'),

    ('potion-of-longevity', 'Potion of Longevity', 40000, 'gp', 0.1,
     "When you drink this potion, your physical age is reduced by 1d6+ 6 years to a minimum of 13 years. Each time you subsequently drink a *Potion of Longevity* there is a 10 percent cumulative chance that you instead age by 1d6 + 6 years."
     "Suspended in this amber liquid is a tiny heart that, against all reason, is still beating. These ingredients vanish when the potion is opened.",
     0, True, 'Very Rare', 'Potion'),

    ('potion-of-mind-reading', 'Potion of Mind Reading', 40000, 'gp', 0.1,
     "When you drink this potion, you gain the effect of the *Detect Thoughts* spell (save DC13) for 10 minutes (no Concentration required)."
     "This potion's dense, purple liquid has an ovoid cloud of pink floating in it.",
     0, True, 'Rare', 'Potion'),

    ('potion-of-pugilism', 'Potion of Pugilism', 400, 'gp', 0.1,
     "After you drink this potion, each Unarmed Strike you make deals an extra 1d6 Force damage on a hit. This effect lasts 10 minutes."
     "This potion is a thick green fluid that tastes like spinach.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-acid-resistance', 'Potion of Acid Resistance', 400, 'gp', 0.1,
     "When you drink this potion, you have resistance to acid damage for 1 hour. "
     "The liquid is murky green and bubbles slightly, giving off a sharp, tangy odor.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-cold-resistance', 'Potion of Cold Resistance', 400, 'gp', 0.1,
     "When you drink this potion, you have resistance to cold damage for 1 hour. "
     "The liquid is icy blue and cold to the touch, with frost clinging to the bottle.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-fire-resistance', 'Potion of Fire Resistance', 400, 'gp', 0.1,
     "When you drink this potion, you have resistance to fire damage for 1 hour. "
     "The liquid is a swirling orange and red, warm to the touch and flickering like flame.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-force-resistance', 'Potion of Force Resistance', 400, 'gp', 0.1,
     "When you drink this potion, you have resistance to force damage for 1 hour. "
     "The liquid is deep violet with occasional ripples of invisible pressure moving through it.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-lightning-resistance', 'Potion of Lightning Resistance', 400, 'gp', 0.1,
     "When you drink this potion, you have resistance to lightning damage for 1 hour. "
     "The liquid crackles faintly and glows with streaks of silver and blue.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-necrotic-resistance', 'Potion of Necrotic Resistance', 400, 'gp', 0.1,
     "When you drink this potion, you have resistance to necrotic damage for 1 hour. "
     "The liquid is pitch black with wisps of shadow swirling within.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-poison-resistance', 'Potion of Poison Resistance', 400, 'gp', 0.1,
     "When you drink this potion, you have resistance to poison damage for 1 hour. "
     "The liquid is sickly green with a bitter smell and slow-moving swirls.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-psychic-resistance', 'Potion of Psychic Resistance', 400, 'gp', 0.1,
     "When you drink this potion, you have resistance to psychic damage for 1 hour. "
     "The liquid pulses with shifting colors and seems to hum faintly in your mind.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-radiant-resistance', 'Potion of Radiant Resistance', 400, 'gp', 0.1,
     "When you drink this potion, you have resistance to radiant damage for 1 hour. "
     "The liquid glows with a soft golden light and feels warm and invigorating.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-thunder-resistance', 'Potion of Thunder Resistance', 400, 'gp', 0.1,
     "When you drink this potion, you have resistance to thunder damage for 1 hour. "
     "The liquid rumbles gently and fizzes with deep, resonant vibrations.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-classic-resistance', 'Potion of Resistance (Classic)', 400, 'gp', 0.1,
     "When you drink this potion, you have resistance to a damage type for 1 hour. The DM chooses the type or determines it randomly by rolling on the following table. "
     "The liquid inside shimmers with ever-changing colors, cycling through hues and textures that hint at different elemental forces. It feels warm, cold, heavy, and light all at once.",
     0, True, 'Uncommon', 'Potion'),

    ('potion-of-speed', 'Potion of Speed', 400, 'gp', 0.1,
     "When you drink this potion, you gain the effect of the *Haste* spell for 1 minute (no Concentration required) without suffering the wave of lethargy that typically occurs when the effect ends."
     "The potion's yello fluid is streaked with black and swirls on its own.",
     0, True, 'Very Rare', 'Potion'),


]

# pg 288+
# 100, 400, 4000, 40000, 200000