# Armor seed rows with armour_category included
ARMOR_ROWS: list[tuple[str, str, int, str, int, bool, int, int, bool, int, str, int, bool, str, str]] = [
    ('leather-armor', 'Leather Armor', 10, 'gp', 11, True, 0, 0, False, 10, '', 0, False, 'Common', 'Light'),
    ('padded-armor', 'Padded Armor', 5, 'gp', 11, True, 0, 0, True, 8, '', 0, False, 'Common', 'Light'),
    ('shield', 'Shield', 10, 'gp', 2, False, 0, 0, False, 6, '', 0, False, 'Common', 'Shield'),
    ('studded-leather-armor', 'Studded Leather Armor', 45, 'gp', 12, True, 0, 0, False, 13, '', 0, False, 'Common', 'Medium'),
    ('leather-armor-plus-one', 'Leather Armor +1', 4000, 'gp', 11, True, 0, 0, False, 10, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Light'),
    ('padded-armor-plus-one', 'Padded Armor +1', 4000, 'gp', 11, True, 0, 0, True, 8, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Light'),
    ('shield-plus-one', 'Shield +1', 4000, 'gp', 2, False, 0, 0, False, 6, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Shield'),
    ('studded-leather-armor-plus-one', 'Studded Leather Armor +1', 4000, 'gp', 12, True, 0, 0, True, 13, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('leather-armor-plus-two', 'Leather Armor +2', 40000, 'gp', 11, True, 0, 0, False, 10, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Light'),
    ('padded-armor-plus-two', 'Padded Armor +2', 40000, 'gp', 11, True, 0, 0, True, 8, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Light'),
    ('shield-plus-two', 'Shield +2', 40000, 'gp', 2, False, 0, 0, False, 6, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Shield'),
    ('studded-leather-armor-plus-two', 'Studded Leather Armor +2', 40000, 'gp', 12, True, 0, 0, False, 13, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('leather-armor-plus-three', 'Leather Armor +3', 200000, 'gp', 11, True, 0, 0, False, 10, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Light'),
    ('padded-armor-plus-three', 'Padded Armor +3', 200000, 'gp', 11, True, 0, 0, True, 8, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Light'),
    ('shield-plus-three', 'Shield +3', 200000, 'gp', 2, False, 0, 0, False, 6, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Shield'),
    ('studded-leather-armor-plus-three', 'Studded Leather Armor +3', 200000, 'gp', 12, True, 0, 0, False, 13, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('breastplate-plus-one', 'Breastplate +1', 4000, 'gp', 14, True, 2, 0, False, 20, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('chain-mail-plus-one', 'Chain Mail +1', 4000, 'gp', 16, False, 0, 13, True, 55, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Heavy'),
    ('chain-shirt-plus-one', 'Chain Shirt +1', 4000, 'gp', 13, True, 2, 0, False, 20, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('half-plate-armor-plus-one', 'Half Plate Armor +1', 4000, 'gp', 15, True, 2, 0, True, 40, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('hide-armor-plus-one', 'Hide Armor +1', 4000, 'gp', 12, True, 2, 0, False, 12, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('plate-armor-plus-one', 'Plate Armor +1', 4000, 'gp', 18, False, 0, 15, True, 65, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Heavy'),
    ('ring-mail-plus-one', 'Ring Mail +1', 4000, 'gp', 14, False, 0, 0, True, 40, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Heavy'),
    ('scale-mail-plus-one', 'Scale Mail +1', 4000, 'gp', 14, True, 2, 0, True, 45, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Medium'),
    ('splint-armor-plus-one', 'Splint Armor +1', 4000, 'gp', 17, False, 0, 15, True, 60, 'You have a +1 bonus to AC while wearing this armor.', 1, True, 'Rare', 'Heavy'),
    ('breastplate-plus-two', 'Breastplate +2', 40000, 'gp', 14, True, 2, 0, False, 20, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('chain-mail-plus-two', 'Chain Mail +2', 40000, 'gp', 16, False, 0, 13, True, 55, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Heavy'),
    ('chain-shirt-plus-two', 'Chain Shirt +2', 40000, 'gp', 13, True, 2, 0, False, 20, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('half-plate-armor-plus-two', 'Half Plate Armor +2', 40000, 'gp', 15, True, 2, 0, True, 40, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('hide-armor-plus-two', 'Hide Armor +2', 40000, 'gp', 12, True, 2, 0, False, 12, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('plate-armor-plus-two', 'Plate Armor +2', 40000, 'gp', 18, False, 0, 15, True, 65, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Heavy'),
    ('ring-mail-plus-two', 'Ring Mail +2', 40000, 'gp', 14, False, 0, 0, True, 40, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Heavy'),
    ('scale-mail-plus-two', 'Scale Mail +2', 40000, 'gp', 14, True, 2, 0, True, 45, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Medium'),
    ('splint-armor-plus-two', 'Splint Armor +2', 40000, 'gp', 17, False, 0, 15, True, 60, 'You have a +2 bonus to AC while wearing this armor.', 2, True, 'Very Rare', 'Heavy'),
    ('breastplate-plus-three', 'Breastplate +3', 200000, 'gp', 14, True, 2, 0, False, 20, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('chain-mail-plus-three', 'Chain Mail +3', 200000, 'gp', 16, False, 0, 13, True, 55, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Heavy'),
    ('chain-shirt-plus-three', 'Chain Shirt +3', 200000, 'gp', 13, True, 2, 0, False, 20, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('half-plate-armor-plus-three', 'Half Plate Armor +3', 200000, 'gp', 15, True, 2, 0, True, 40, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('hide-armor-plus-three', 'Hide Armor +3', 200000, 'gp', 12, True, 2, 0, False, 12, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('plate-armor-plus-three', 'Plate Armor +3', 200000, 'gp', 18, False, 0, 15, True, 65, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Heavy'),
    ('ring-mail-plus-three', 'Ring Mail +3', 200000, 'gp', 14, False, 0, 0, True, 40, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Heavy'),
    ('scale-mail-plus-three', 'Scale Mail +3', 200000, 'gp', 14, True, 2, 0, True, 45, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Medium'),
    ('splint-armor-plus-three', 'Splint Armor +3', 200000, 'gp', 17, False, 0, 15, True, 60, 'You have a +3 bonus to AC while wearing this armor.', 3, True, 'Legendary', 'Heavy'),
    ('adamantine-breastplate', 'Adamantine Breastplate', 400, 'gp', 14, True, 2, 0, False, 20, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Medium'),
    ('adamantine-chain-mail', 'Adamantine Chain Mail', 400, 'gp', 16, False, 0, 13, True, 55, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Heavy'),
    ('adamantine-chain-shirt', 'Adamantine Chain Shirt', 400, 'gp', 13, True, 2, 0, False, 20, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Medium'),
    ('adamantine-half-plate-armor', 'Adamantine Half Plate Armor', 400, 'gp', 15, True, 2, 0, True, 40, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Medium'),
    ('adamantine-plate-armor', 'Adamantine Plate Armor', 400, 'gp', 18, False, 0, 15, True, 65, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Heavy'),
    ('adamantine-ring-mail', 'Adamantine Ring Mail', 400, 'gp', 14, False, 0, 0, True, 40, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Heavy'),
    ('adamantine-scale-mail', 'Adamantine Scale Mail', 400, 'gp', 14, True, 2, 0, True, 45, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Medium'),
    ('adamantine-splint-armor', 'Adamantine Splint Armor', 400, 'gp', 17, False, 0, 15, True, 60, 'This suit of armor is reinforced with adamantine, one of the hardest substances in existence. While you’re wearing it, any\xa0Critical Hit\xa0against you becomes a normal hit.', 0, True, 'Uncommon', 'Heavy'),
]
